### ISSUE TITLE
Build a new version?

### ISSUE THREAD

**Issue by blink1073** [conda-forge/icu-feedstock#27]
We are unable to upgrade Node to v14 because it require version 65+ of this library, cf https://github.com/conda-forge/nodejs-feedstock/pull/126.    The source library is at [v67.1](https://github.com/unicode-org/icu/releases).  Does anyone have the bandwidth to create a new release?

**Comment by ocefpaf** [comment]
I gave it a shot but the upstream URL changes the hash in every interaction! I'll try again later but this seems more work that I can do at the moment.

**Comment by blink1073** [comment]
Wow, that is odd.  Thanks for trying @ocefpaf!

**Comment by minrk** [comment]
looks like github-releases is the official download source now, so hopefully that solves the hash issue: #28

**Comment by ocefpaf** [comment]
> looks like github-releases is the official download source now, so hopefully that solves the hash issue: #28

Thanks @minrk!
