### ISSUE TITLE
Bad symlinks in latest OSX build (56.1-3)

### ISSUE THREAD

**Issue by lentils** [conda-forge/icu-feedstock#9]
First off, `conda-forge` seems great so far! But I've noticed some packages have some build artifacts leftover that cause problems:

```
jboshard ~ => conda create -n test-icu icu=56.1=3
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment /Users/jboshard/anaconda/envs/test-icu:

The following NEW packages will be INSTALLED:

    icu: 56.1-3 conda-forge

Proceed ([y]/n)? 

Linking packages ...
An unexpected error has occurred, please consider sending the                                                                                                               |   0%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/jboshard/anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Users/jboshard/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/Users/jboshard/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/Users/jboshard/anaconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 57, in execute
    install(args, parser, 'create')
  File "/Users/jboshard/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "/Users/jboshard/anaconda/lib/python2.7/site-packages/conda/plan.py", line 595, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/Users/jboshard/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 136, in execute_instructions
    cmd(state, arg)
  File "/Users/jboshard/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 79, in LINK_CMD
    link(state['prefix'], dist, lt, index=state['index'], shortcuts=shortcuts)
  File "/Users/jboshard/anaconda/lib/python2.7/site-packages/conda/install.py", line 1066, in link
    _link(src, dst, lt)
  File "/Users/jboshard/anaconda/lib/python2.7/site-packages/conda/install.py", line 209, in _link
    shutil.copy2(src, dst)
  File "/Users/jboshard/anaconda/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/Users/jboshard/anaconda/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/Users/jboshard/anaconda/pkgs/icu-56.1-3/bin/activate'
```

If you follow the error, you can see that some of the scripts in `bin` are symlinks:
```
jboshard ~ => ls -l /Users/jboshard/anaconda/pkgs/icu-56.1-3/bin/
total 1168
lrwxr-xr-x  1 jboshard  admin      37 Jun 28 09:48 activate -> /Users/travis/miniconda3/bin/activate
lrwxr-xr-x  1 jboshard  admin      34 Jun 28 09:48 conda -> /Users/travis/miniconda3/bin/conda
lrwxr-xr-x  1 jboshard  admin      39 Jun 28 09:48 deactivate -> /Users/travis/miniconda3/bin/deactivate
-rwxr-xr-x  1 jboshard  admin   41148 Jun 26 16:46 derb
-rwxr-xr-x  1 jboshard  admin   23332 Jun 26 16:46 genbrk
-rwxr-xr-x  1 jboshard  admin   22460 Jun 26 16:46 gencfu
-rwxr-xr-x  1 jboshard  admin   32408 Jun 26 16:46 gencnval
-rwxr-xr-x  1 jboshard  admin   37504 Jun 26 16:46 gendict
-rwxr-xr-x  1 jboshard  admin  233676 Jun 26 16:46 genrb
-rwxr-xr-x  1 jboshard  admin   22662 Jun 26 16:46 icu-config
-rwxr-xr-x  1 jboshard  admin   18016 Jun 26 16:46 icuinfo
-rwxr-xr-x  1 jboshard  admin   70144 Jun 26 16:46 makeconv
-rwxr-xr-x  1 jboshard  admin   61108 Jun 26 16:46 pkgdata
```

This doesn't seem to be a problem on Linux, so I'm guessing this is a bug from the Travis build on OSX. Furthermore, looks like version 56.1-2 doesn't have any `activate`, `conda` or `deactivate` scripts at all:
```
jboshard ~ => ls -l /Users/jboshard/anaconda/pkgs/icu-56.1-2/bin/
total 1040
-rwxr-xr-x  3 jboshard  admin   32932 Apr  5 17:17 derb
-rwxr-xr-x  3 jboshard  admin   15116 Apr  5 17:17 genbrk
-rwxr-xr-x  3 jboshard  admin   14236 Apr  5 17:17 gencfu
-rwxr-xr-x  3 jboshard  admin   28296 Apr  5 17:17 gencnval
-rwxr-xr-x  3 jboshard  admin   33376 Apr  5 17:17 gendict
-rwxr-xr-x  3 jboshard  admin  229508 Apr  5 17:17 genrb
-rwxr-xr-x  1 jboshard  admin   22647 Apr  5 17:17 icu-config
-rwxr-xr-x  3 jboshard  admin   13904 Apr  5 17:17 icuinfo
-rwxr-xr-x  3 jboshard  admin   61936 Apr  5 17:17 makeconv
-rwxr-xr-x  3 jboshard  admin   56988 Apr  5 17:17 pkgdata
```

Based on this I'm assuming we don't want any reference to those three scripts at all.

**Comment by lentils** [comment]
I did a little digging and found this commit: https://github.com/conda-forge/icu-feedstock/commit/6cfe4e5731d96c7828719fb88ca6871b312fc38c

Looks like this was the one that introduced the new build number, and the only suspect I can find is the added `toolchain` build dependency. I don't know anything about that package, but maybe that is persisting those symlinks?

**Comment by jakirkham** [comment]
Thanks for point thing out to us. This is an easy fix. It actually is an issue with `conda` and `conda-build` being pinned to relatively distant versions and the use of activation scripts during. I'll add a PR to fix it.

**Comment by lentils** [comment]
Great to hear. Thank you for such a quick reply!

**Comment by jakirkham** [comment]
Yeah, we went through this circus before ( https://github.com/conda-forge/hdf5-feedstock/issues/23 ). So, we are better prepared this time. I'll go ahead and remove the broken package. Please see PR ( https://github.com/conda-forge/icu-feedstock/pull/10 ) for the fix.

**Comment by lentils** [comment]
Yes, that was the other package we ran into issues with! Will be sure to alert you if we find any more.

**Comment by jakirkham** [comment]
Ah, sorry about that fiasco. Please do.

Actually, instead of removing it. I have changed the label to "broken" for now. I hope that is ok. This should allow others to look at it if needed and feels a bit more community friend IMHO. Though as it is not under "main" it should not install. I have verified that this works as intend for me locally.

To downgrade try doing `conda install icu=56.1=2`.

**Comment by lentils** [comment]
Preserving the package for others sounds fine to me. I'm not sure I understand what you mean by "label" in this context, though. Can you explain that?

Thanks for the workaround.

**Comment by jakirkham** [comment]
Sure, see this [blog post]( https://www.continuum.io/blog/developer-blog/anaconda-cloud-introducing-labels ).

**Comment by jakirkham** [comment]
See this screenshot for an example.

![screen shot 2016-06-28 at 14 51 31](https://cloud.githubusercontent.com/assets/3019665/16428445/e3cd4388-3d3f-11e6-941c-026ea839c519.png)

Basically, one would have to do something like `conda install -c conda-forge/label/broken icu` to get the bad package. So, it shouldn't happen by default.

**Comment by lentils** [comment]
Ah, got it. That's a cool feature I didn't know about.
